apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-fee-payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: college-fee-payment
  template:
    metadata:
      labels:
        app: college-fee-payment
    spec:
      containers:
      - name: php-container
        image: college-fee-payment-system:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "your-rds-endpoint"
        - name: DB_USER
          value: "your-db-username"
        - name: DB_PASSWORD
          value: "your-db-password"
        - name: DB_NAME
          value: "stufeedb"
