apiVersion: v1
kind: Service
metadata:
  name: college-fee-payment-service
spec:
  selector:
    app: college-fee-payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
